training:
    n_epochs: 200
    ngpu: 1
    optim_steps: 20
    plot_freq: 4


optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: false

model:
    name: fb3p
    layer_dim: 128
    delta: 0.1
    t: 3
    t1: 53
    t2: 105
    nt: 157 
    r: 0.9
    k: 2
    n: [2048, 2048]
    pi: [0.25, 0.75]
    h: [0.2, 0.5]
    sigma: [0.1, 0.15]
    zeta: [1.75, 1.25]
    gamma_cur: [1.25, 1.75]
    gamma_prev: [1.25, 1.75]
    v: [0.6 , 0.2]
    m: [0.1, 0.1]
    beta: [1, 1]

